### ISSUE TITLE
Inversion Solution meta improvement

### ISSUE THREAD

**Issue by benjamineac** [GNS-Science/simple-toshi-ui#291]
The current inversion solution meta displayed is hard to read and has more data than is always necessary.

**Done when:**
- [x] Keys are bold
- [x] Each item wraps nicely, no splitting over two lines
- [x] If it has a _tag_ property, only show the tag unless mousing over. Then show whole object (in tooltip?).

**Comment by benjamineac** [comment]
Fix: strings with 'True' or 'False' were causing the JSON to not parse and the tooltips to not appear. 
Casting the booleans to lowercase solves this issue.
