### ISSUE TITLE
EPIC: implement react-hooks-linter 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/simple-toshi-ui#302]
We want to use the linter to watch over all our hooks, But we have a bunch of files that need fixing first.

This ticket is the master list, its will close when each of the following known files is lint-free (with QA from @0y) AND when the linter is added to main branch...

Dev, pls make ref to this ticket in any PRs where you're including a Hook-fix ...

**The list ...**

 - [ ] src/components/FileDetail.tsx
 - [ ] src/components/Find.tsx
 - [ ] src/components/FindResult.tsx
 - [ ] src/components/common/DialogAlert.tsx
 - [ ] src/components/common/MultiSelect.tsx  [ All files this line and above resolved by this PR](https://github.com/GNS-Science/simple-toshi-ui/pull/303)
 - [ ] src/pages/InversionSolution.tsx
 - [ ] src/pages/MySolutions.tsx
 - [ ] src/pages/PreviewLineMFD.tsx
 - [ ] src/pages/PreviewMFD.tsx
 - [ ] src/pages/SolutionAnalysisPreview.tsx [ All src/pages/* files resolved in this PR](https://github.com/GNS-Science/simple-toshi-ui/pull/305)
 - [ ] src/components/diagnosticReportView/DiagnosticReportCard.tsx [This file is resolved by this PR](https://github.com/GNS-Science/simple-toshi-ui/pull/308/files)
 - [ ] src/components/diagnosticReportView/GeneralViewMfd.tsx
 - [ ] src/components//generalTask/GeneralTaskChidlrenTab.tsx
 - [ ] src/components//generalTask/SweepArgumentFilter.tsx 
 - [ ] src/hooks/useShortcute.tsx
 - [ ] src/componetns/inversionSolution/InversionSolutionHazardCharts.tsx
 - [ ] src/componetns/inversionSolution/InversionSolutionMfdTab.tsx
 - [ ] src/componetns/inversionSolution/InversionSolutionAnalysisTab.tsx
 - [ ] src/componetns/inversionSolution/charts/HazardCurves.tsx
 - [ ] src/componetns/inversionSolution/charts/MfdChart.tsx
