### ISSUE TITLE
EPIC: Add Scaled Inversion (SIS) Solution Support to toshi ui

### ISSUE THREAD

**Issue by 0qy** [GNS-Science/simple-toshi-ui#329]
Adding scaled inversion solution support to the app involves adding support for every aspect of the app, please create PR to `epic/392_scaled-IS-support` branch

- [x] [Add SIS page with the link `ScaledSolution/${id}`](https://github.com/GNS-Science/simple-toshi-ui/issues/326)
- [ ] [Add Search Support](https://github.com/GNS-Science/simple-toshi-ui/issues/330)
- [x] [Add Find Support](https://github.com/GNS-Science/simple-toshi-ui/issues/331)
- [x] [Add Flipchart Support](https://github.com/GNS-Science/simple-toshi-ui/issues/328)
- [x] Add MySolutions - Favourites Support*

**Comment by chrisdicaprio** [comment]
Sample data in TEST can be found in GT ID R2VuZXJhbFRhc2s6MTAwMjUx. Diagnostics have been run for all ScaledInversionSolutions; figures to display should be availble
