### ISSUE TITLE
EPIC: Add Scaled Inversion (SIS) Solution Support to Toshi ui

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/simple-toshi-ui#394]
Adding time dependent inversion solution support to the app involves  ...

- [ ] Add TDIS page with the link `TimeDependentSolution/${id}`
- [ ] TDIS Flipchart Support
- [ ] [Add TDIS Find Support
- [ ] Add TDIS Search Support
- [ ] Add MySolutions - Favourites Support

**Example GT**: R2VuZXJhbFRhc2s6MTAxMzY4 (TEST) has Solution Diagnostics run

**Query example**

```query {
  node(id:"VGltZURlcGVuZGVudEludmVyc2lvblNvbHV0aW9uOjEwMTM1Ng==") {
    __typename
    ... on FileInterface {
      file_name
      file_size
    }
  }
}```
