### ISSUE TITLE
Feature: Filter control for subtask list using swept args to provide simple choices to used

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/simple-toshi-ui#74]
We want to filter long list of subtasks from the GT child task view

So that users can focus on the areas of interest and so we can experiment with views composed from selected task outputs.

**Done when:**

 - [x] user choices based on the content of 'swept args' 
      - [x] i.e. one field per swept arg
      - [x] choices for each control are limited to those in each swept_arg 
 - [x] the list of child tasks is filtered according to the choices made

Suggestions:
  - https://npm.io/search/keyword:facet 
  - https://npm.io/package/react-input-faceted
  - https://npm.io/package/react-facet-filter
  - https://npm.io/package/lazy-facet
